apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: shaky-lemur-nodejs 
  janus-idp.io/tekton: shaky-lemur-nodejs
  backstage.io/kubernetes-id: shaky-lemur-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: shaky-lemur-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  