apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: shaky-lemur-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shaky-lemur-nodejs 
  name: shaky-lemur-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: shaky-lemur-nodejs 
